"use client";
import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,ArrowUpRight,Activity,Building2,ChartNoAxesCombined,Check,ChevronDown,Database,Download,Factory,Layers3,RefreshCw,Server,ShieldCheck,TriangleAlert,Zap} from 'lucide-react';
import {ResponsiveContainer,ComposedChart,Line,Bar,XAxis,YAxis,CartesianGrid,Tooltip,Brush,ReferenceLine} from 'recharts';
import type {IndustryDataset,MetricDefinition,MetricObservation,Recommendation} from '@/lib/industry/types';
import {metricStats,chartRows,generateRecommendations,levelLabels,RULE_VERSION} from '@/lib/industry/engine.mjs';
import {appBase} from '@/lib/runtime';
import {beijing,format} from '@/lib/data';
import './industry.css';

const tabs=[['overview','产业总览'],['metrics','指标看板'],['companies','公司对比'],['conclusions','投资结论'],['sources','数据说明']];
const categories=[['capex','云厂商资本开支'],['cloud','云业务需求'],['projects','数据中心建设'],['power','电力与基础设施'],['servers','服务器与网络设备'],['semiconductor','半导体需求'],['costs','上游成本']];
const labels:Record<string,string>={reported:'已披露',calculated:'已计算',guidance:'公司指引',official:'官方数据',project_announcement:'公告数据',third_party:'第三方估计',proxy:'代理指标',demo:'演示数据'};
const statusLabels:Record<string,string>={ready:'已获取',cached:'获取失败 · 展示缓存',fetch_failed:'获取失败',pending:'待接入',authorization_required:'待授权数据源'};
const freq:Record<string,string>={daily:'日度',monthly:'月度',quarterly:'季度',annual:'年度',event:'事件'};
const color=['#167c68','#5b80b2','#c39848','#9e7cb0','#d38067','#6b9b9d'];
const empty:IndustryDataset={schemaVersion:'1',generatedAt:'',definitions:[],series:{},projects:[],events:[]};
const pct=(v:number|null|undefined,unit='%')=>v==null?'—':`${v>0?'↑ ':v<0?'↓ ':'→ '}${format(Math.abs(v))}${unit}`;
const displayTime=(value:string|null|undefined)=>value&&value.length===10?value+'（来源仅记录日期）':beijing(value);
const conf=(v:string)=>({high:'高',medium:'中',low:'低'}[v]??v);
function title(id:string,data:IndustryDataset){const d=data.definitions.find(d=>d.id===id);return d?`${d.entity??''} ${d.nameZh}`:id;}
function labelLevel(v:string){return (levelLabels as Record<string,string>)[v]??v;}
function useClock(){const [value,setValue]=useState(()=>new Date().toISOString());useEffect(()=>{const timer=setInterval(()=>setValue(new Date().toISOString()),60000);return()=>clearInterval(timer)},[]);return value;}
export default function Industry(){
 const [data,setData]=useState<IndustryDataset>(empty),[loading,setLoading]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState('overview'),[category,setCategory]=useState('capex'),[search,setSearch]=useState('');const now=useClock();
 async function refresh(){setLoading(true);try{const url=appBase()==='/'?'/api/industry':appBase()+'data/industry.json';const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw Error('industry cache unavailable');const payload=await response.json() as IndustryDataset;if(!Array.isArray(payload.definitions)||!payload.series)throw Error('invalid cache');setData(payload);setError('')}catch{setError('产业数据缓存暂时无法读取。已有数据仍保留，可稍后检查更新。')}finally{setLoading(false)}}
 useEffect(()=>{void refresh();const read=()=>{const p=new URLSearchParams(location.search);setTab(tabs.some(t=>t[0]===p.get('industry'))?p.get('industry')!:'overview');if(categories.some(c=>c[0]===p.get('category')))setCategory(p.get('category')!)};read();addEventListener('popstate',read);const timer=setInterval(()=>void refresh(),300000);return()=>{removeEventListener('popstate',read);clearInterval(timer)}},[]);
 const recommendations=useMemo(()=>generateRecommendations(data,now,data.recommendations??[]) as Recommendation[],[data,now]);
 function navigate(next:string,cat?:string,id?:string){setTab(next);if(cat)setCategory(cat);const p=new URLSearchParams(location.search);p.set('page','impact');p.set('industry',next);if(cat)p.set('category',cat);history.pushState({},'',appBase()+'?'+p.toString()+(id?'#'+id:''));if(id){setSearch('');setTimeout(()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'}),150)}else window.scrollTo({top:0,behavior:'smooth'})}
 function showMetric(id:string){const def=data.definitions.find(d=>d.id===id);if(def)navigate('metrics',def.category,id)}
 const connected=data.definitions.filter(d=>data.series[d.id]?.observations.some(p=>p.value!=null)).length;
 return <section className="industry-module" aria-label="AI产业链关键指标">
  <div className="industry-toolbar"><div><span className="industry-live"/><strong>{connected}</strong> 已接入指标 <span className="industry-separator">/</span> {data.definitions.length} 项指标目录 <span className="industry-separator">/</span> <span>后台检查 {data.generatedAt?displayTime(data.generatedAt):'尚未取得缓存'}</span></div><button className="industry-button" onClick={()=>void refresh()} disabled={loading}><RefreshCw size={14} className={loading?'spinning':''}/>{loading?'检查中':'检查产业数据'}</button></div>
  <nav className="industry-tabs" aria-label="产业模块导航">{tabs.map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} className={tab===id?'selected':''} onClick={()=>navigate(id)}>{label}</button>)}</nav>
  {error&&<div className="industry-alert" role="alert"><TriangleAlert size={17}/>{error}</div>}
  {!data.generatedAt&&!error?<div className="industry-empty">正在读取产业数据与来源记录…</div>:<>
  {tab==='overview'&&<Overview data={data} recommendations={recommendations} now={now} navigate={navigate} showMetric={showMetric}/>}
  {tab==='metrics'&&<><div className="industry-controls"><label>产业环节<select value={category} onChange={e=>navigate('metrics',e.target.value)}>{categories.map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><label className="industry-search">搜索公司或指标<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="如 Microsoft、资本开支、铜"/></label></div>{category==='capex'&&<CompanyComparison data={data} capexOnly/>}{category==='projects'&&<ProjectPanel data={data}/>}{category==='costs'&&<CostComparison data={data}/>}
   <div className="industry-chart-grid">{data.definitions.filter(d=>d.category===category&&`${d.nameZh} ${d.entity} ${d.nameEn}`.toLowerCase().includes(search.toLowerCase())).map(d=><MetricCard key={d.id} def={d} data={data} now={now} recommendations={recommendations}/>)}</div>
   {!data.definitions.some(d=>d.category===category)&&<div className="industry-empty">该环节尚未接入可验证指标。</div>}</>}
  {tab==='companies'&&<CompanyComparison data={data}/>}
  {tab==='conclusions'&&<><div className="industry-section-title"><div><h2>产业配置建议</h2><p>透明规则 {RULE_VERSION} · 未来1—2个季度 · 不生成个股买卖建议</p></div><span className="industry-tag">产业趋势 ≠ 收益保证</span></div><div className="industry-recommendation-grid">{recommendations.map(r=><RecommendationCard key={r.targetId} recommendation={r} data={data} showMetric={showMetric}/>)}</div><History data={data}/></>}
  {tab==='sources'&&<Sources data={data} now={now}/>}
  </>}
 </section>
}
function Overview({data,recommendations,now,navigate,showMetric}:{data:IndustryDataset;recommendations:Recommendation[];now:string;navigate:(t:string,c?:string,id?:string)=>void;showMetric:(id:string)=>void}){
 const states=[{category:'capex',target:'cloud',icon:Layers3,id:'MSFT.capex',name:'云厂商资本开支'}, {category:'cloud',target:'cloud',icon:Activity,id:'GOOG.cloud_revenue',name:'云业务需求'},{category:'projects',target:'data_centers',icon:Building2,id:'PROJECT.operational_capacity',name:'数据中心建设'},{category:'power',target:'power',icon:Zap,id:'EIA.VA.commercial',name:'电力与基础设施'},{category:'servers',target:'servers',icon:Server,id:'DELL.ai_server_revenue',name:'服务器需求'},{category:'semiconductor',target:'accelerators',icon:Factory,id:'NVDA.datacenter_revenue',name:'半导体需求'}];
 const stats=data.definitions.map(d=>({d,s:metricStats(d,data.series[d.id]?.observations??[],now)})).filter(x=>x.s.latest?.value!=null);
 const changed=[...stats].filter(x=>x.s.yoy!=null&&x.d.unit!=='%').sort((a,b)=>Math.abs(b.s.yoy!)-Math.abs(a.s.yoy!)).slice(0,5);
 const updated=[...stats].sort((a,b)=>(data.series[b.d.id]?.fetchedAt??'').localeCompare(data.series[a.d.id]?.fetchedAt??'')).slice(0,5);
 const problems=data.definitions.filter(d=>['cached','fetch_failed'].includes(data.series[d.id]?.status)||metricStats(d,data.series[d.id]?.observations??[],now).freshness==='stale');
 const overall=recommendations.find(r=>r.targetId==='overall')!;
 return <>
  <div className="industry-hero"><div><span className="industry-kicker">从投资投入，到盈利兑现</span><h2>把产业变化，变成可验证的判断。</h2><p>沿着资本开支、建设进度、设备需求和盈利兑现寻找证据。每个结论都保留反向信号与失效条件。</p><button onClick={()=>navigate('conclusions')}>查看投资结论 <ArrowRight size={16}/></button></div><div className="industry-hero-status"><span>AI产业链整体</span><strong>{labelLevel(overall?.level??'insufficient_data')}</strong><small>置信度 {conf(overall?.confidence??'low')} · 未来1—2个季度</small><p>{overall?.reason}</p></div></div>
  <div className="industry-state-grid">{states.map(({category,target,icon:Icon,id,name})=>{const d=data.definitions.find(d=>d.id===id),s=d?metricStats(d,data.series[id]?.observations??[],now):null,r=recommendations.find(r=>r.targetId===target);return <button className="industry-state-card" key={category} onClick={()=>navigate('metrics',category,id)}><div className="industry-state-title"><Icon size={18}/><h3>{name}</h3><ArrowUpRight size={15}/></div><span className="industry-card-subtitle">{d?`${d.entity??''} · ${d.nameZh}`:'公开项目样本 · 不代表全球市场'}</span><strong className="industry-number">{format(s?.latest?.value)} <small>{d?.unit??'MW'}</small></strong><div className="industry-state-changes"><span>同比 {pct(s?.yoy)}</span><span>环比 {pct(s?.qoq)}</span></div><div className="industry-state-period">观测期 {s?.latest?.periodEnd??'数据不足'} · {s?.freshness==='fresh'?'在正常更新周期内':s?.freshness==='stale'?'已超过更新周期':'待接入'}</div><div className="industry-state-bottom"><span>数据趋势 <b>{s?.trend??'数据不足'}</b></span><span>配置倾向 <b>{labelLevel(r?.level??'insufficient_data')}</b> · 置信度{conf(r?.confidence??'low')}</span></div></button>})}</div>
  <div className="industry-section-title"><div><h2>投入有没有变成需求？</h2><p>趋势是指标状态；配置倾向需要多项证据共同支持。</p></div><button className="industry-text-button" onClick={()=>navigate('metrics','capex')}>全部指标 <ArrowRight size={14}/></button></div>
  <div className="industry-chain">{['云厂商资本开支','数据中心与电力建设','服务器、GPU、存储与网络','半导体生产与库存','云业务收入与利润','产业配置建议'].map((v,i)=><div key={v}><span>{String(i+1).padStart(2,'0')}</span><strong>{v}</strong>{i<5&&<ArrowRight size={16}/>}</div>)}</div>
  <div className="industry-recommendation-grid">{recommendations.filter(r=>['cloud','servers','accelerators','power'].includes(r.targetId)).map(r=><RecommendationCard compact key={r.targetId} recommendation={r} data={data} showMetric={showMetric}/>)}</div>
  <div className="industry-two-col"><MiniList title="最近更新的五项指标" rows={updated} data={data} showMetric={showMetric}/><MiniList title="同比变化幅度最大的五项" rows={changed} data={data} showMetric={showMetric} changes/></div>
  <div className="industry-two-col"><section className="industry-panel"><h3>即将发布</h3>{data.events.filter(e=>e.kind==='release'&&e.date>=now.slice(0,10)&&e.isConfirmed).length?data.events.filter(e=>e.kind==='release'&&e.date>=now.slice(0,10)&&e.isConfirmed).map(e=><p key={e.id}><a href={e.sourceUrl} target="_blank" rel="noreferrer">{e.date} · {e.entity} · {e.title} ↗</a></p>):<p className="industry-muted">尚未接入可自动核验的公司财报日历；不以推测日期代替正式公告。</p>}<p className="industry-small">未公告的财报时间显示未知。</p></section><section className="industry-panel"><h3>数据获取与有效性</h3><p>{problems.length?`${problems.length} 项指标获取失败或超过正常更新周期。`:'已接入指标未发现超过正常更新周期的记录。'}</p><p className="industry-muted">{data.definitions.filter(d=>!data.series[d.id]?.observations.length).length} 项尚待接入或授权。数据不足是正常状态。</p><button className="industry-text-button" onClick={()=>navigate('sources')}>查看异常与来源 <ArrowRight size={14}/></button></section></div><History data={data}/>
 </>
}
function MiniList({title:heading,rows,data,showMetric,changes=false}:{title:string;rows:any[];data:IndustryDataset;showMetric:(id:string)=>void;changes?:boolean}){return <section className="industry-panel"><h3>{heading}</h3>{changes&&<p className="industry-small">按非百分比指标的同比绝对幅度排序；不代表投资重要性，不混排绝对数值。</p>}{rows.map(({d,s})=><button className="industry-update-row" key={d.id} onClick={()=>showMetric(d.id)}><span>{d.entity} · {d.nameZh}<small>{s.latest.periodEnd} · {changes?'同比口径':displayTime(data.series[d.id]?.fetchedAt)}</small></span><strong>{changes?pct(s.yoy,d.unit==='%'&&d.family!=='cloud_growth'?'个百分点':'%'):format(s.latest.value)+' '+d.unit}</strong><ArrowUpRight size={14}/></button>)}</section>}
function RecommendationCard({recommendation:r,data,showMetric,compact=false}:{recommendation:Recommendation;data:IndustryDataset;showMetric:(id:string)=>void;compact?:boolean}){const evidence=(items:any[],fallback:string)=><ul>{items.length?items.slice(0,compact?2:30).map(e=><li key={e.metricId}><button className="industry-evidence-link" onClick={()=>showMetric(e.metricId)}>{e.explanation} <ArrowUpRight size={12}/></button>{!compact&&<small>版本 {e.observationVersion.slice(0,16)} · {e.periodEnd}</small>}</li>):<li className="industry-muted">{fallback}</li>}</ul>;return <article className="industry-recommendation"><div className="industry-rec-top"><span>{r.targetName}</span><ShieldCheck size={17}/></div><h3 className={'industry-rating '+r.level}>{r.level==='insufficient_data'?<Database size={19}/>:r.level==='positive_allocation'?<Check size={19}/>:<ChartNoAxesCombined size={19}/>} {labelLevel(r.level)}</h3><div className="industry-rec-meta">置信度 {conf(r.confidence)} · 未来1—2个季度 <span>数据截止 {r.dataCutoffAt||'尚无可用证据'}</span></div><p className="industry-rec-reason">{r.reason}</p><div className="industry-dimensions">{r.dimensions.map(d=><div key={d.id}><span>{d.name}</span><strong>{({positive:'＋ 正面',negative:'－ 负面',neutral:'↔ 中性',missing:'○ 数据不足'})[d.state]}</strong>{!compact&&d.metricIds.map(id=><button key={id} onClick={()=>showMetric(id)}>{title(id,data)} ↗</button>)}</div>)}</div><div className="industry-evidence-grid"><div><h4>核心依据</h4>{evidence(r.positiveEvidence,'尚无满足规则的正面证据。')}</div><div><h4>反向证据</h4>{evidence(r.negativeEvidence,'未检出有效反向证据，不代表风险不存在。')}</div></div>{!compact&&r.neutralEvidence.length>0&&<details><summary>中性证据（{r.neutralEvidence.length}）</summary>{evidence(r.neutralEvidence,'')}</details>}<details open={!compact}><summary>失效条件与后续观察</summary><ul>{r.invalidationConditions.map(v=><li key={v}>{v}</li>)}</ul><p className="industry-small">可用核心指标 {Math.round(r.coverage*100)}%；缺失或不适用 {r.missingMetrics.length} 项。</p><div className="industry-watch-list">{r.watchMetrics.slice(0,compact?4:24).map(id=><button onClick={()=>showMetric(id)} key={id}>{title(id,data)} ↗</button>)}</div></details><div className="industry-rec-footer">规则 {r.ruleVersion} · 生成 {displayTime(r.generatedAt)}<small>建议 ID {r.id}</small></div></article>}
function MetricCard({def:d,data,now,recommendations}:{def:MetricDefinition;data:IndustryDataset;now:string;recommendations:Recommendation[]}){
 const [range,setRange]=useState('all'),[mode,setMode]=useState('value'),[frequency,setFrequency]=useState(d.frequency),[style,setStyle]=useState(d.frequency==='quarterly'?'bar':'line'),[visible,setVisible]=useState(true),[csv,setCsv]=useState('');const s=data.series[d.id],obs=s?.observations??[];const st=metricStats(d,obs,now);const rows=useMemo(()=>chartRows(d,obs,{range,mode,frequency}),[d,obs,range,mode,frequency]);const has=obs.some(p=>p.value!=null);const unit=mode==='value'?d.unit:d.unit==='%'?'个百分点':'%';const change=st.yoy==null?'缺少同比基期，暂不描述同比方向。':`${st.latest?.periodEnd} ${d.family==='cloud_growth'?'披露同比增速':'同比'} ${st.yoy>0?'上升':st.yoy<0?'下降':'持平'} ${format(Math.abs(st.yoy))}${d.unit==='%'&&d.family!=='cloud_growth'?'个百分点':'%'}；${st.previousYoy==null?'尚缺上期同比基期。':`同比变化较上一期${st.yoy>=st.previousYoy?'上升':'下降'} ${format(Math.abs(st.yoy-st.previousYoy))} 个百分点。`}`;
 const rangePoints=obs.filter(p=>p.periodEnd>=(rows[0]?.periodEnd??'')&&p.value!=null);const startValue=rangePoints[0]?.value,endValue=rangePoints.at(-1)?.value;const rangeChange=startValue!=null&&endValue!=null?(d.unit==='%'?endValue-startValue:startValue>0?(endValue/startValue-1)*100:null):null;
 const impacts=recommendations.flatMap(r=>[...r.positiveEvidence,...r.negativeEvidence,...r.neutralEvidence].filter(e=>e.metricId===d.id).map(e=>r.targetName+'：'+({positive:'正面',negative:'负面',neutral:'中性'}[e.direction])+'证据'));
 function download(){if(!d.exportAllowed)return;const cells=(v:unknown)=>'"'+String(v??'').replaceAll('"','""')+'"';const header=['metric','period_start','period_end','fiscal_period','value','unit','display_mode','value_type','source','published_at','fetched_at','observation_version','formula','original_items'];const text='\ufeff'+[header,...rows.map((p:any)=>[d.id,p.periodStart,p.periodEnd,p.fiscalPeriod,p.value,unit,mode,d.valueType,p.sourceUrl,p.publishedAt,p.fetchedAt,p.version,p.formula,JSON.stringify(p.originalItems??{})])].map(row=>row.map(cells).join(',')).join('\r\n');setCsv(text);const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=d.id+'-'+mode+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <article id={d.id} className="industry-chart-card" aria-label={`${d.entity??''} ${d.nameZh}`}><div className="industry-chart-heading"><div><span className="industry-company">{d.entity??'产业统计'}</span><h3>{d.nameZh}</h3><p>{d.nameEn}</p></div><span className="industry-tag">{labels[d.valueType]}</span></div><div className="industry-metric-value"><strong>{format(st.latest?.value)}</strong><span>{d.unit}</span><span className={'industry-status '+(s?.status==='ready'?'':'warning')}>{statusLabels[s?.status??'pending']}{st.freshness==='stale'?' · 已过期':''}</span></div><div className="industry-metric-summary"><span>同比 {pct(st.yoy,d.unit==='%'&&d.family!=='cloud_growth'?'个百分点':'%')}</span><span>{d.frequency==='quarterly'?'季环比':'环比'} {pct(st.qoq,d.unit==='%'?'个百分点':'%')}</span><span>区间变化 {pct(rangeChange,d.unit==='%'?'个百分点':'%')}</span><span>{freq[d.frequency]} · {st.latest?.fiscalPeriod??st.latest?.periodEnd??'尚无观测'}</span></div>
 {has?<><div className="industry-chart-controls"><div className="industry-segmented">{[['1','1年'],['3','3年'],['5','5年'],['all','全部']].map(([v,n])=><button key={v} aria-pressed={range===v} disabled={v!=='all'&&!!obs[0]&&(Date.parse(obs.at(-1)!.periodEnd)-Date.parse(obs[0].periodEnd))/86400000<Number(v)*365} onClick={()=>setRange(v)}>{n}</button>)}</div><label className="industry-visually-hidden" htmlFor={d.id+'-mode'}>数值口径</label><select id={d.id+'-mode'} aria-label="数值口径" value={mode} onChange={e=>setMode(e.target.value)}><option value="value">原始值</option><option value="yoy" disabled={d.family==='cloud_growth'}>同比</option><option value="qoq" disabled={d.family==='cloud_growth'}>环比</option></select><select aria-label="显示频率" value={frequency} onChange={e=>setFrequency(e.target.value as MetricDefinition['frequency'])}><option value={d.frequency}>{freq[d.frequency]}</option>{d.frequency==='monthly'&&d.aggregation!=='none'&&<><option value="quarterly">{d.aggregation==='sum'?'季度合计':'季度均值'}</option><option value="annual">{d.aggregation==='sum'?'年度合计':'年度均值'}</option></>}</select><button title="切换折线/柱状" aria-label="切换折线或柱状图" onClick={()=>setStyle(v=>v==='line'?'bar':'line')}><ChartNoAxesCombined size={16}/></button></div><div className="industry-chart-area"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={rows} margin={{top:12,right:10,bottom:0,left:-15}}><CartesianGrid vertical={false} stroke="#e4ece9" strokeDasharray="3 4"/><XAxis dataKey="periodEnd" tickFormatter={v=>v.slice(2,7)} minTickGap={45} tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10}} tickFormatter={v=>format(v,0)} axisLine={false} tickLine={false}/><Tooltip labelFormatter={v=>String(v)} formatter={(v)=>[format(Number(v))+' '+unit,d.nameZh]}/>{mode!=='value'&&<ReferenceLine y={0} stroke="#a8bbb4"/>}{visible&&(style==='bar'?<Bar dataKey="value" name={d.nameZh} fill="#78b5a6" maxBarSize={30} isAnimationActive={false}/>:<Line dataKey="value" name={d.nameZh} stroke="#167c68" strokeWidth={2} dot={rows.length<18} connectNulls={false} isAnimationActive={false}/>)}{rows.length>4&&<Brush dataKey="periodEnd" height={20} travellerWidth={8} tickFormatter={v=>v.slice(0,7)} stroke="#b3cbc1"/>}</ComposedChart></ResponsiveContainer></div><div className="industry-chart-bottom"><button aria-pressed={visible} onClick={()=>setVisible(v=>!v)}>{visible?'●':'○'} {d.nameZh}</button><span>{rows[0]?.periodEnd} — {rows.at(-1)?.periodEnd} · {unit}</span><button disabled={!d.exportAllowed} onClick={download}><Download size={13}/> {d.exportAllowed?'CSV':'待核验导出许可'}</button></div></>:<div className="industry-empty"><Database size={27}/><strong>{statusLabels[s?.status??'pending']}</strong><p>{s?.note??s?.error??'尚未取得稳定且可核验的数据，不使用零或模拟值补齐。'}</p></div>}
 <>{csv&&<details open className="industry-csv-preview"><summary>CSV 预览（若浏览器未保存，可复制以下内容）</summary><textarea aria-label="CSV 导出内容" readOnly value={csv} rows={5}/><button className="industry-button" onClick={()=>setCsv('')}>关闭预览</button></details>}</><div className="industry-metric-explanation"><p><strong>发生了什么变化</strong>{change}</p><p><strong>指标含义与产业位置</strong>{d.interpretation??d.methodology}</p><p><strong>可能的传导机制</strong>{d.transmission??transmission(d)}</p><p><strong>需要交叉验证</strong>{d.crossCheck??'结合云厂商投入、业务收入、订单、现金流和成本判断；单一指标不能证明因果关系。'}</p><p><strong>对当前建议的影响</strong>{impacts.length?impacts.slice(0,3).join('；'):'当前不参与有效建议：缺少历史基期、数据有效性或关键交叉证据。'}</p></div><details><summary>来源、口径与观测版本 <ChevronDown size={13}/></summary><p>{d.methodology}</p><p>来源：<a href={d.sourceUrl} target="_blank" rel="noreferrer">{d.sourceName} ↗</a> · {d.currency??'原始单位，无汇率转换'}</p><p>最新观测区间：{st.latest?.periodStart??'—'} → {st.latest?.periodEnd??'—'}</p><p>来源发布时间：{displayTime(st.latest?.publishedAt??st.latest?.filingDate)}<br/>最近成功获取：{displayTime(s?.fetchedAt)}<br/>最近检查：{displayTime(s?.checkedAt)}</p><p>公式：{st.latest?.formula??'来源直接披露；无额外转换。'}</p><pre>{JSON.stringify(st.latest?.originalItems??{},null,2)}</pre><p>观测版本：{st.latest?.version??'—'}{st.latest?.isRestated?' · 已修订':''}</p>{st.latest?.sourceUrl&&<a target="_blank" rel="noreferrer" href={st.latest.sourceUrl}>打开这一期的原始来源 ↗</a>}{s?.error&&<p>最近失败：{s.error}</p>}</details><div className="industry-source-footer">{freq[d.frequency]} · {d.sourceName}<span>成功获取 {displayTime(s?.fetchedAt)}</span></div></article>
}
function transmission(d:MetricDefinition){if(d.family==='capex')return '资本投入变化可能传导至机房、服务器和芯片采购；公司总资本开支不等于纯AI投入，需核对项目建设和收入兑现。';if(d.category==='costs'||d.family==='electricity')return '价格变化可能改变材料或运营成本，也可能反映供给、天气和需求变化；不同产业环节的影响方向不同。';if(d.category==='cloud')return '云业务收入和利润用于检验前期投入是否兑现；不同公司的业务边界、租赁和订单定义需要分别核对。';return '收入、订单和库存的共同变化可提供产业需求线索，仍需核对交付、毛利率和客户集中度。'}
function CompanyComparison({data,capexOnly=false}:{data:IndustryDataset;capexOnly?:boolean}){
 const [family,setFamily]=useState('capex'),[mode,setMode]=useState('value'),[selected,setSelected]=useState(['MSFT','GOOG','AMZN','META','ORCL']),[range,setRange]=useState('all');const families=[['capex','资本开支'],['capex_ratio','资本开支/收入'],['cloud_revenue','云业务收入'],['cloud_margin','云业务利润率'],['cloud_growth','Azure披露增速'],['datacenter_revenue','数据中心业务收入'],['backlog','订单余额'],['inventory','库存'],['gross_margin','毛利率'],['operating_cash_flow','营业现金流'],['free_cash_flow','自由现金流']];
 const defs=data.definitions.filter(d=>d.family===family&&d.frequency==='quarterly');const entities=[...new Set(defs.map(d=>d.entity).filter(Boolean))] as string[];const chosen=defs.filter(d=>selected.includes(d.entity!));const units=[...new Set(chosen.map(d=>d.unit))];
 const rows=useMemo(()=>{const converted=chosen.map(d=>chartRows(d,data.series[d.id]?.observations??[],{mode:mode==='yoy'?'yoy':mode==='qoq'?'qoq':'value',range}));const quarters=new Set<string>();const maps=converted.map((obs:any[])=>new Map(obs.map(p=>{const q=p.periodEnd.slice(0,4)+'Q'+Math.ceil(Number(p.periodEnd.slice(5,7))/3);quarters.add(q);return [q,p]})));const common=[...quarters].sort().find(q=>maps.every(m=>m.get(q)?.value!=null&&m.get(q).value>0));return [...quarters].sort().map(q=>({quarter:q,...Object.fromEntries(chosen.flatMap((d,i)=>{const p=maps[i].get(q);let v=p?.value??null;if(mode==='normalized')v=common&&q>=common&&v!=null?v/maps[i].get(common).value*100:null;return [[d.id,v],[d.id+'_period',p?.periodStart+' → '+p?.periodEnd],[d.id+'_fiscal',p?.fiscalPeriod]]}))}))},[data,chosen.map(d=>d.id).join(','),mode,range]);
 const canSum=family==='capex'&&mode==='value'&&chosen.length===5&&selected.length===5&&['MSFT','GOOG','AMZN','META','ORCL'].every(e=>selected.includes(e));const sumRows=canSum?rows.filter(r=>chosen.every(d=>(r as any)[d.id]!=null)):[];
 return <section className="industry-panel industry-company-panel"><div className="industry-section-title"><div><h2>{capexOnly?'五家云厂商资本开支':'公司对比'}</h2><p>按公司报告期末所在自然季度定位，保留实际起止日期。不是严格同期排名。</p></div><span className="industry-tag">原始币种 · 无汇率换算</span></div><div className="industry-controls"><label>对比指标<select value={family} onChange={e=>{setFamily(e.target.value);setRange('all');setSelected([...new Set(data.definitions.filter(d=>d.family===e.target.value&&d.entity).map(d=>d.entity!))])}}>{families.filter(([id])=>!capexOnly||['capex','capex_ratio','operating_cash_flow'].includes(id)).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><label>显示口径<select value={mode} onChange={e=>setMode(e.target.value)}><option value="value">原始数值</option><option value="yoy">同比变化</option><option value="qoq">环比变化</option><option value="normalized">共同起始报告季度＝100</option></select></label><label>时间范围<select value={range} onChange={e=>setRange(e.target.value)}><option value="all">全部可用</option>{[1,3,5].map(year=><option key={year} value={String(year)} disabled={!chosen.length||chosen.some(d=>{const pts=data.series[d.id]?.observations??[];return pts.length<2||(Date.parse(pts.at(-1)!.periodEnd)-Date.parse(pts[0].periodEnd))/86400000<year*365})}>近{year}年</option>)}</select></label></div><div className="industry-company-selector">{entities.map((e,i)=><label key={e}><input type="checkbox" checked={selected.includes(e)} onChange={()=>setSelected(s=>s.includes(e)?s.filter(x=>x!==e):[...s,e])}/><i style={{background:color[i%color.length]}}/>{e}</label>)}</div><div className="industry-alert subdued"><ShieldCheck size={17}/><span>现金购置固定资产与融资租赁分别看。{family==='cloud_revenue'?'Microsoft Intelligent Cloud 不是 Azure 单项收入；Oracle IaaS+SaaS、AWS、Google Cloud 业务边界不同。':'财年季度与自然季度不等同，鼠标悬停可查看每家公司的实际报告期。'}{chosen.some(d=>!d.isComparableAcrossEntities)&&' 所选指标存在口径差异，不做简单排名。'}</span></div>
 {units.length>1?<div className="industry-empty">所选指标单位不同，请分别查看，不能合并同一数值轴。</div>:<div className="industry-comparison-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={rows} margin={{left:0,right:15,top:15}}><CartesianGrid vertical={false} stroke="#e5ede9" strokeDasharray="3 4"/><XAxis dataKey="quarter" tick={{fontSize:11}}/><YAxis tick={{fontSize:10}} width={55}/><Tooltip content={({active,payload,label})=>active&&payload?.length?<div className="industry-tooltip"><strong>{label} · 期末落点</strong>{payload.map((p:any)=><p key={p.dataKey}>{p.name}: {format(p.value)}<small>{p.payload[p.dataKey+'_fiscal']} · {p.payload[p.dataKey+'_period']}</small></p>)}</div>:null}/>{chosen.map((d,i)=>mode==='value'?<Bar key={d.id} dataKey={d.id} name={d.entity} fill={color[i%color.length]} maxBarSize={26} isAnimationActive={false}/>:<Line key={d.id} dataKey={d.id} name={d.entity} stroke={color[i%color.length]} dot connectNulls={false} isAnimationActive={false}/>)}</ComposedChart></ResponsiveContainer></div>}
 <p className="industry-small">纵轴单位：{mode==='normalized'?'起点=100':mode==='value'?units[0]??'—':units[0]==='%'?'个百分点':'%'}。缺失观测留空，不用增速与绝对金额相加。{mode==='normalized'&&' 仅从所有已选公司都有正值的共同报告季度开始；财季起止仍可能不一致。'}</p>
 {canSum&&<details><summary>五家公司资本开支合计（报告期末季度归组，非严格同期总额）</summary><p className="industry-small">仅在五家公司都有数据时汇总。Oracle 财季偏移，租赁口径仍需分别查阅；合计不代表纯AI资本开支。</p>{sumRows.length?<div className="industry-comparison-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={sumRows}><XAxis dataKey="quarter"/><YAxis/><Tooltip/>{chosen.map((d,i)=><Bar key={d.id} dataKey={d.id} name={d.entity} stackId="capex" fill={color[i]}/>)}</ComposedChart></ResponsiveContainer></div>:<p>尚无五家公司同时齐备的报告季度，暂不计算合计。</p>}</details>}
 <div className="industry-table-wrap"><table><thead><tr><th>公司</th><th>实际报告期间</th><th>财年季度</th><th>最新值</th><th>来源与口径</th></tr></thead><tbody>{chosen.map(d=>{const p=data.series[d.id]?.observations.at(-1);return <tr key={d.id}><td>{d.entity}</td><td>{p?.periodStart??'—'} → {p?.periodEnd??'—'}</td><td>{p?.fiscalPeriod??'—'}</td><td>{format(p?.value)} {d.unit}</td><td><a href={p?.sourceUrl??d.sourceUrl} target="_blank" rel="noreferrer">{d.nameZh} ↗</a><small>{p?.basis??d.methodology}</small></td></tr>})}</tbody></table></div><p className="industry-company-disclaimer">本页用于观察公司经营与产业环境。尚未完整纳入股价、估值、市场一致预期、资产负债风险和重大事件，因此不生成任何公司的买入或卖出建议。</p></section>
}
function CostComparison({data}:{data:IndustryDataset}){const defs=data.definitions.filter(d=>['WB.copper','WB.aluminum','WB.natural_gas','EIA.VA.commercial'].includes(d.id));const maps=defs.map(d=>new Map((data.series[d.id]?.observations??[]).map(p=>[p.periodEnd.slice(0,7),p.value])));const months=[...new Set(maps.flatMap(m=>[...m.keys()]))].sort().filter(date=>maps.every(m=>m.get(date)!=null&&m.get(date)!>0));const chosen=months.slice(-37);const rows=chosen.map(date=>({date,...Object.fromEntries(defs.map((d,i)=>[d.id,maps[i].get(date)!/maps[i].get(chosen[0])!*100]))}));return <section className="industry-panel"><h3>上游成本对比 · 共同起点＝100</h3><p className="industry-small">统一月度频率 · 仅共同月份 · 不混合美元/公吨、美元/MMBtu与美分/kWh原始坐标轴</p><div className="industry-comparison-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={rows}><XAxis dataKey="date" tick={{fontSize:10}} minTickGap={45}/><YAxis tick={{fontSize:10}}/><Tooltip/><ReferenceLine y={100} stroke="#b7c9c1"/>{defs.map((d,i)=><Line key={d.id} dataKey={d.id} name={d.nameZh} stroke={color[i]} dot={false}/>)}</ComposedChart></ResponsiveContainer></div><div className="industry-table-wrap"><table><thead><tr><th>指标</th><th>原始价格</th><th>1个月</th><th>3个月</th><th>12个月/同比</th></tr></thead><tbody>{defs.map(d=>{const obs=data.series[d.id]?.observations??[];const last=obs.at(-1);const change=(months:number)=>{if(!last)return null;const dt=new Date(last.periodEnd);dt.setUTCDate(1);dt.setUTCMonth(dt.getUTCMonth()-months);const p=obs.find(p=>p.periodEnd.slice(0,7)===dt.toISOString().slice(0,7));return p?.value&&last.value!=null?(last.value/p.value-1)*100:null};return <tr key={d.id}><td>{d.nameZh}</td><td>{format(last?.value)} {d.unit}</td><td>{pct(change(1))}</td><td>{pct(change(3))}</td><td>{pct(change(12))}</td></tr>})}</tbody></table></div></section>}
function ProjectPanel({data}:{data:IndustryDataset}){return <section className="industry-panel"><h3>公开数据中心项目登记</h3><p>按项目唯一ID去重，允许保存多个官方来源。公告投资额、规划容量与已投运容量分别保存，不把规划等同于交付。</p>{data.projects.length?<div className="industry-table-wrap"><table><thead><tr><th>项目 / 主体</th><th>地区</th><th>状态</th><th>容量 MW</th><th>预计投运</th><th>来源 / 核验</th></tr></thead><tbody>{data.projects.map(p=><tr key={p.id}><td>{p.name}<small>{p.owner}</small></td><td>{p.country} {p.region}</td><td>{p.status}</td><td>{p.powerCapacityMw??'未披露'}</td><td>{p.expectedOperationalAt??'未披露'}</td><td>{p.sourceUrls.map(u=><a key={u} href={u} target="_blank" rel="noreferrer">官方来源 ↗ </a>)}<small>{p.lastVerifiedAt}</small></td></tr>)}</tbody></table></div>:<div className="industry-empty"><Building2 size={29}/><strong>项目数据库待接入</strong><p>尚无经过完整去重、状态和容量核验的公开项目样本。各地区均为数据不足，不显示零。</p></div>}</section>}
function History({data}:{data:IndustryDataset}){const history=[...(data.recommendationHistory??[])].sort((a,b)=>b.generatedAt.localeCompare(a.generatedAt)).slice(0,10);return <section className="industry-panel"><h3>建议版本与变化原因</h3><p className="industry-small">从本模块首次运行开始保存；不回填假设性的历史评级。</p>{history.length?<div className="industry-table-wrap"><table><thead><tr><th>生成时间</th><th>产业环节</th><th>建议变化</th><th>原因与规则</th></tr></thead><tbody>{history.map(r=><tr key={r.id+'-'+r.generatedAt}><td>{displayTime(r.generatedAt)}</td><td>{r.targetName}</td><td>{r.previousLevel?labelLevel(r.previousLevel)+' → ':''}{labelLevel(r.level)}</td><td>{r.changeReason}<small>{r.ruleVersion} · {r.id}</small></td></tr>)}</tbody></table></div>:<p className="industry-muted">首次建议正在建立，尚无历史变化记录。</p>}</section>}
function Sources({data,now}:{data:IndustryDataset;now:string}){return <><div className="industry-two-col"><section className="industry-panel"><h3>数据、时间与修订</h3><p>报告期末、财年季度、来源发布日期与获取时间分别保存。现金流年度累计值只有在基期匹配时才能差分为单季。</p><p>同比 = 本期/上年同期 − 1；环比 = 本期/上期 − 1。百分比指标的变化以百分点解释。缺基期或非正基期时不计算变化率。</p><p>从首次获取开始记录新修订。首次历史导入代表当前可得数据，不代表过去当时已知数据。</p></section><section className="industry-panel"><h3>建议规则 {RULE_VERSION}</h3><p>五维度分别展示投入、需求、建设、盈利和成本。至少四维正面且无负面、五维完整时才可积极配置；三维正面时分批关注。持续恶化需至少两个报告期。</p><p>关键维度缺失、可用指标不足70%、来源过期或只有一家公司的证据时，暂不形成建议。演示数据、管理层预测与未经验证的第三方估计不参与正式计算。</p><p>规则按产业环节选取指标；成本上涨对制造端与上游矿业不是同一含义。本版不凭商品涨价推荐矿业配置。</p></section><section className="industry-panel"><h3>后台更新</h3><p>GitHub Actions 独立于网页约每30分钟运行；财报和月度数据源按24小时缓存检查新文件，失败保留最后成功数据并重试。调度可能延迟。</p><p>当前财报发布日历尚未自动接入，采用每日官方文件检查；Dell、AMD、NVIDIA与Oracle目前使用已核验的报告地址清单，新财报地址仍需维护。来源未披露发布日期则留空，不把抓取时间冒充发布时间。</p><p>数据与建议版本保存在独立 data-cache 分支。网页刷新只重读后台缓存。</p></section><section className="industry-panel"><h3>使用边界</h3><p>公司总资本开支不是纯AI投入；Intelligent Cloud不等同Azure；Meta广告收入不能与云收入相加；全球半导体统计不等于AI芯片需求。</p><p>全国与州级商业/工业平均电价不是数据中心合同价。SIA/WSTS完整历史、HBM现货/合约价、全球项目全量、实时封装产能等需进一步落实授权。</p><p>产业配置建议不等于收益保证；个股功能仍缺行情、估值、一致预期、财务风险和重大事件的完整联合校验。</p></section></div><section className="industry-panel"><h3>全部指标与来源状态</h3><div className="industry-type-key">{Object.entries(labels).map(([k,v])=><span className="industry-tag" key={k}>{v}</span>)}</div><div className="industry-table-wrap"><table><thead><tr><th>指标 / 来源</th><th>类型 / 口径</th><th>频率 / 单位</th><th>最新期 / 获取时间</th><th>状态 / 许可</th></tr></thead><tbody>{data.definitions.map(d=>{const s=data.series[d.id],st=metricStats(d,s?.observations??[],now);return <tr key={d.id}><td>{d.entity} · {d.nameZh}<small>{d.id}</small><a href={d.sourceUrl} target="_blank" rel="noreferrer">{d.sourceName} ↗</a></td><td>{labels[d.valueType]}<small>{d.methodology}</small></td><td>{freq[d.frequency]} · {d.unit}<small>{d.currency??'无币种转换'}</small></td><td>{st.latest?.periodEnd??'尚无观测'}<small>{displayTime(s?.fetchedAt)}</small></td><td>{statusLabels[s?.status??'pending']}{st.freshness==='stale'?' · 过期':''}<small>{d.exportAllowed?'事实数值CSV可导出':'导出待核验许可'}</small>{s?.error&&<small>{s.error}</small>}</td></tr>})}</tbody></table></div></section></>}
