"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {useEffect,useMemo,useState} from 'react';
import {CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {format,beijing} from '@/lib/data';
import {WATCHLIST_STORAGE_KEY,normalizeWatchPreferences,filterResearchWatchlist} from '@/lib/industry/watchlist-preferences.mjs';
import {valuationScenario} from '@/lib/industry/valuation.mjs';
import './research-tools.css';
const num=(v:any)=>v==null?'—':format(v);
const pct=(v:any)=>v==null?'—':`${v>0?'+':''}${format(v)}%`;

export function ResearchAttention({research,showMetric}:{research:any;showMetric:(id:string)=>void}){
 const targets=research.quantitative?.sectorSignals??[];
 const defaults=targets.map((s:any)=>s.targetId);
 const [preferences,setPreferences]=useState<any>(()=>normalizeWatchPreferences(null,defaults)),[loaded,setLoaded]=useState(false),[unreadOnly,setUnreadOnly]=useState(false),[storageError,setStorageError]=useState(false),[limit,setLimit]=useState(20);
 useEffect(()=>{try{const raw=localStorage.getItem(WATCHLIST_STORAGE_KEY);setPreferences(normalizeWatchPreferences(raw?JSON.parse(raw):null,defaults));}catch{setStorageError(true);}setLoaded(true);},[]); // Initial browser preference only; data refresh must not reset it.
 useEffect(()=>{if(!loaded)return;try{localStorage.setItem(WATCHLIST_STORAGE_KEY,JSON.stringify(preferences));}catch{setStorageError(true);}},[loaded,preferences]);
 const events=filterResearchWatchlist(research.attention?.events??[],{...preferences,unreadOnly});
 const companies=[...new Set([...(research.valuation?.companies??[]).map((c:any)=>c.entity),...(research.attention?.events??[]).flatMap((e:any)=>e.entities)])].filter(Boolean) as string[];
 const toggle=(field:string,id:string)=>setPreferences((p:any)=>({...p,[field]:p[field].includes(id)?p[field].filter((x:string)=>x!==id):[...p[field],id]}));
 const read=(id:string)=>toggle('readIds',id);
 return <div className="research-tools"><div className="research-tools-heading"><div><h3>今天值得关注什么</h3><p>{research.attention?.method??'正在准备重要变化清单。'}</p></div><label className="research-check"><input type="checkbox" checked={unreadOnly} onChange={e=>setUnreadOnly(e.target.checked)}/>仅看未读</label></div>
  <details className="research-tool-box"><summary>我的关注范围 · {preferences.targetIds.length} 个产业 / 样本，{preferences.entities.length} 家公司</summary><div className="research-chip-list">{targets.map((s:any)=><label key={s.targetId}><input type="checkbox" checked={preferences.targetIds.includes(s.targetId)} onChange={()=>toggle('targetIds',s.targetId)}/>{s.targetName}</label>)}</div><div className="research-chip-list">{companies.map(entity=><label key={entity}><input type="checkbox" checked={preferences.entities.includes(entity)} onChange={()=>toggle('entities',entity)}/>{entity}</label>)}</div><button className="research-small-button" onClick={()=>setPreferences((p:any)=>({...p,targetIds:[],entities:[]}))}>清空关注</button><button className="research-small-button" onClick={()=>setPreferences((p:any)=>({...p,targetIds:defaults}))}>关注全部产业</button></details>
  {storageError&&<p>本浏览器暂不能保存偏好，本次选择仍可使用。</p>}
  <p className="industry-small">{events.length} 条符合关注范围。网页打开后读取后台变化；已读状态不会因刷新反复重置。</p>
  <div className="research-tools-grid">{events.slice(0,limit).map((event:any)=><article key={event.id} className={`research-tool-box research-attention-event ${event.read?'is-read':''}`}><div className="research-tools-heading"><span className="industry-tag">{event.priority>=3?'优先核对':event.priority===2?'值得关注':'新披露'}</span><small>{event.date}</small></div><h4>{event.title}</h4><p>{event.description}</p>{event.reason&&<p className="industry-small">{event.reason}</p>}<div className="research-tool-actions">{event.metricIds.slice(0,2).map((id:string)=><button key={id} onClick={()=>showMetric(id)}>查看对应指标 ↗</button>)}{event.sourceUrl&&<a href={event.sourceUrl} target="_blank" rel="noreferrer">原始来源 ↗</a>}<button onClick={()=>read(event.id)}>{event.read?'标为未读':'标为已读'}</button></div></article>)}</div>
  {!events.length&&<p className="research-tool-box">当前关注范围内暂无{unreadOnly?'未读的':''}重要变化。可展开上方选择关注对象。</p>}{events.length>limit&&<button className="research-small-button" onClick={()=>setLimit(limit+20)}>再显示 20 条</button>}
 </div>;
}

export function ResearchRobustness({data}:{data:any}){
 return <div className="research-tools"><h3>结论是否依赖某个假设</h3><p>{data?.method??'等待后台完成稳健性计算。'}</p><div className="research-tools-grid">{(data?.targets??[]).map((row:any)=><article className="research-tool-box" key={row.targetId}><h4>{row.targetName}</h4><div className="research-metric-strip"><span>当前研究分<b>{num(row.baselineScore)}</b></span><span>有效重算范围<b>{num(row.scoreRange?.min)} — {num(row.scoreRange?.max)}</b></span><span>失去正式资格<b>{row.eligibilityLossCount??0} 种情况</b></span></div><p>{row.summary}</p><p className="industry-small">方向改变 {row.directionFlipCount??0} 次 · 共 {row.scenarioCount??0} 个扰动检验。缺少必需证据时保留资格丢失，不将空值计为零。</p><details><summary>哪些变化影响最大</summary><p>最敏感因子：{row.mostSensitiveFactor?.name??row.mostSensitiveFactor?.label??row.mostSensitiveFactor?.factorId??'暂无'}；主体：{row.mostSensitiveEntity?.name??row.mostSensitiveEntity?.entity??row.mostSensitiveEntity?.label??'暂无'}。</p><div className="research-progress-table"><table><thead><tr><th>检验条件</th><th>重算分数</th><th>变化</th><th>结果</th></tr></thead><tbody>{(row.scenarios??[]).map((s:any)=><tr key={s.id}><td>{s.label??s.name??s.id}</td><td>{num(s.score)}</td><td>{num(s.delta)}</td><td>{s.eligible===false?'证据不足，暂停正式评分':s.directionFlipped?'方向改变':'保留评分'}{s.reason&&<small>{s.reason}</small>}</td></tr>)}</tbody></table></div></details></article>)}</div><details className="research-tool-box"><summary>如何理解这项检验</summary><ul>{(data?.limitations??[]).map((s:string)=><li key={s}>{s}</li>)}</ul></details></div>;
}

export function ResearchValidation({data}:{data:any}){
 return <div className="research-tools"><h3>这些分数有没有参考价值</h3><p>{data?.summary??'等待可验证的真实存档与后续表现。'}</p><p className="industry-small">验证规则登记：{data?.registeredAt?beijing(data.registeredAt):'等待首次登记'}。此前记录只做探索分析；之后按固定规则积累前瞻样本。</p><div className="research-tool-box"><p>{data?.method}</p><p>观察顺序：真实保存结论 → 之后完整交易日开始 → 等待期满 → 剔除时间重叠 → 比较分数组与成本情景。</p></div>
  {(data?.groups??[]).length>0?<div className="research-tools-grid">{data.groups.map((group:any,i:number)=><article className="research-tool-box" key={group.id??i}><h4>{group.targetName??group.targetId} · {group.months} 个月</h4><p>{group.evaluationPhase==='prospective'?'规则登记后的前瞻样本':'规则登记前的探索样本'} · {group.tier==='formal'?'正式分':'先行分'}</p><p>{group.summary??group.status}</p><div className="research-progress-table"><table><thead><tr><th>预设分数组</th><th>不重叠样本</th><th>平均超额</th></tr></thead><tbody>{(group.scoreGroups??group.bands??[]).map((b:any)=><tr key={b.id??b.name}><td>{b.name??b.label??b.id}</td><td>{b.count}</td><td>{pct(b.meanExcessReturn)}</td></tr>)}</tbody></table></div><details><summary>费用与样本外检查</summary><p>{group.walkForward?.summary??group.walkForward?.reason??'等待更早已期满的训练样本与随后独立测试样本。'}</p>{(group.costSensitivity??[]).map((c:any)=><p key={c.costBpsPerSide??c.costBps}>单侧费用 {c.costBpsPerSide??c.costBps} 基点：平均扣费收益 {pct(c.meanNetReturn)}，平均超额 {pct(c.meanExcessReturn)}。</p>)}</details></article>)}</div>:<p className="research-tool-box">尚无满足登记规则的期满样本。后台会继续保存，期满后自动计算；当前不显示未经验证的胜率。</p>}
  <details className="research-tool-box"><summary>样本排除与验证口径</summary><ul>{(data?.limitations??[]).map((s:string)=><li key={s}>{s}</li>)}</ul>{(data?.excluded??[]).slice(0,30).map((e:any,i:number)=><p key={i}>{e.targetName??e.targetId??e.cohortId}：{e.reason??e.code}</p>)}</details>
 </div>;
}

export function ResearchValuationContext({company}:{company:any}){
 const [growth,setGrowth]=useState('0'),[margin,setMargin]=useState(''),[fcfMargin,setFcfMargin]=useState('');
 useEffect(()=>{setGrowth('0');setMargin('');setFcfMargin('');},[company?.entity]);
 const value=(text:string)=>text.trim()===''?null:Number(text);
 // The implementation accepts numeric optional assumptions. The imported JavaScript
 // module has no declaration file, so retain the runtime values while keeping the
 // client component's type-check boundary explicit.
 const scenario=useMemo(()=>company?valuationScenario(company,{revenueGrowthPct:Number(growth),netMarginPct:value(margin) as any,fcfMarginPct:value(fcfMargin) as any}):null,[company,growth,margin,fcfMargin]);
 const activeScenario:any=scenario?.status==='available'?scenario.scenario:null;
 const history=company?.history;
 if(!company)return null;
 const metric=(key:string,label:string,suffix:string)=>{const row=history?.metrics?.[key];return <span key={key}>{label}<b>{row?.percentile==null?'等待更多历史':`${num(row.percentile)}% 分位`}</b><small>{row?.count??0} 个有效日期</small>{suffix&&<em>{suffix}</em>}</span>};
 return <section className="research-valuation-context"><h4>历史位置与经营情景</h4><p className="research-progress-note">{history?.method??'尚无可用历史估值。'} {history?.note}</p><div className="research-metric-strip research-tool-box">{metric('pe','P/E',history?.metrics?.pe?.median==null?'':`中位数 ${num(history.metrics.pe.median)} 倍`)}{metric('ps','P/S',history?.metrics?.ps?.median==null?'':`中位数 ${num(history.metrics.ps.median)} 倍`)}{metric('fcfYield','FCF收益率',history?.metrics?.fcfYield?.median==null?'':`中位数 ${num(history.metrics.fcfYield.median)}%`)}</div>
 {history?.observations?.length>1&&<div className="research-history-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={history.observations} margin={{top:8,right:12,bottom:8,left:0}}><CartesianGrid stroke="#e0ebe5" strokeDasharray="3 5"/><XAxis dataKey="date" tickFormatter={(v:string)=>v.slice(5)} minTickGap={35} fontSize={12}/><YAxis fontSize={12}/><Tooltip labelFormatter={v=>String(v)} formatter={(v:any,name:any)=>[num(Number(v)),name]}/><Line dataKey="pe" name="P/E" stroke="#167c68" dot={false} connectNulls isAnimationActive={false}/><Line dataKey="ps" name="P/S" stroke="#4b74b8" dot={false} connectNulls isAnimationActive={false}/></LineChart></ResponsiveContainer></div>}
 <details className="research-tool-box"><summary>按固定市值试算增长和利润率</summary><p>用当前已核验市值不变的假设，查看收入增长和利润率改变后，对应倍数怎样变化。它不预测股价、也不生成目标价。</p><div className="research-scenario-inputs"><label>收入增长（%）<input type="number" value={growth} onChange={e=>setGrowth(e.target.value)} /></label><label>净利率（%，可选）<input type="number" value={margin} placeholder={scenario?.baseline?.netMarginPct==null?'需同口径财务':'沿用当前'} onChange={e=>setMargin(e.target.value)} /></label><label>FCF利润率（%，可选）<input type="number" value={fcfMargin} placeholder={scenario?.baseline?.fcfMarginPct==null?'需同口径财务':'沿用当前'} onChange={e=>setFcfMargin(e.target.value)} /></label></div>{activeScenario?<div className="research-metric-strip"><span>情景 P/E<b>{activeScenario.pe==null?'不适用':`${num(activeScenario.pe)} 倍`}</b></span><span>情景 P/S<b>{num(activeScenario.ps)} 倍</b></span><span>情景 FCF收益率<b>{activeScenario.fcfYield==null?'—':`${num(activeScenario.fcfYield)}%`}</b></span></div>:<p>{scenario?.reason??'等待可计算的市值与TTM财务。'}</p>}<p className="industry-small">{scenario?.method}</p></details>
 </section>;
}

export function ResearchCrossCompany({data,showMetric}:{data:any;showMetric:(id:string)=>void}){
 return <div className="research-tools"><h3>多家公司是否相互印证</h3><p>{data?.method}</p>{(data?.groups??[]).map((group:any)=><article className="research-tool-box" key={group.id}><h4>{group.name}</h4><p><strong>{group.summary}</strong></p><div className="research-tools-grid">{group.companies.map((c:any)=><div key={c.entity} className="research-peer"><h4>{c.entity}</h4><p>{c.scope}</p>{[c.revenue,c.profit].filter(Boolean).map((m:any)=><div key={m.id}><button className="research-link-button" onClick={()=>showMetric(m.id)}>{m.name} ↗</button><p><strong>{num(m.value)} {m.unit}</strong> · {m.unit==='%'?'同比变化':'同比'} {m.yoy==null?'待核验':`${m.yoy>0?'+':''}${num(m.yoy)}${m.unit==='%'?' 个百分点':'%'}`}</p><small>{m.periodStart??''} → {m.periodEnd??'—'} · 公布 {m.publishedAt?.slice(0,10)??'未知'} · {m.status==='cached'?'使用缓存':m.status==='ready'?'已获取':'来源待核验'}</small>{m.reason&&<p>{m.reason}</p>}<a href={m.sourceUrl} target="_blank" rel="noreferrer">官方来源 ↗</a></div>)}{!c.revenue&&<p>尚未取得通过校验的公开历史，未参与交叉判断。</p>}</div>)}</div><p className="industry-small">{group.boundary}</p></article>)}</div>;
}

export function ResearchModelEvaluation({data}:{data:any}){
 const contract=data?.contract,actual=data?.live?.evaluation;
 return <div className="research-tools"><h3>推理模型接入与评测</h3><div className="research-metric-strip research-tool-box"><span>程序验收题<b>{contract?.passedCount??0} / {contract?.totalCount??0}</b></span><span>实际成功调用<b>{data?.activation?.successfulCalls??0} 次</b></span><span>实际模型版本<b>{data?.activation?.resolvedModel??'尚未调用'}</b></span></div><p>{data?.live?.note}</p><p className="industry-small">{contract?.note}</p>{actual&&<div className="research-tool-box"><p>引用版本匹配 {actual.citations?.matched}/{actual.citations?.total}；反向说明覆盖 {num(actual.contraryCaseCoverage*100)}%；三情景覆盖 {num(actual.scenarioCoverage*100)}%。</p><p>{actual.meaning}</p></div>}<div className="research-tools-grid"><details className="research-tool-box"><summary>固定验收题</summary>{(contract?.cases??[]).map((c:any)=><p key={c.id}>{c.passed?'✓':'!'} {c.name} · {c.expected==='accept'?'应接收':'应拦截'} / {c.actual==='accept'?'已接收':'已拦截'}</p>)}</details><div className="research-tool-box"><h4>实际启用后仍需检查</h4><ul>{(data?.reviewChecklist??[]).map((s:string)=><li key={s}>{s}</li>)}</ul><p>当前接口已经接好；账户和密钥需在后台配置，网页不接收密钥。</p>{data?.sourceUrl&&<a href={data.sourceUrl} target="_blank" rel="noreferrer">OpenAI 官方评测说明 ↗</a>}</div></div></div>;
}
