// Visible placeholders are part of the catalog, never zero-filled series.
const source={company:'https://www.sec.gov/search-filings',eia:'https://www.eia.gov/electricity/data/',wsts:'https://www.wsts.org/67/Historical-Billings-Report',projects:'https://www.energy.gov/'};
export const pendingMetrics=[
 ['MSFT.azure_revenue','Azure单项季度收入','Azure standalone quarterly revenue','cloud','azure_revenue','MSFT','亿美元','quarterly','reported','公司未稳定单独披露可比季度金额；Intelligent Cloud不冒充Azure。'],
 ['MSFT.backlog','商业剩余履约义务','Commercial remaining performance obligations','cloud','backlog','MSFT','亿美元','quarterly','reported','待核对合同范围、确认期限和历史口径。'],
 ['AMZN.backlog','AWS订单/合同余额','AWS backlog','cloud','backlog','AMZN','亿美元','quarterly','reported','待接入正式披露的合同口径。'],
 ['GOOG.backlog','Google Cloud订单余额','Google Cloud backlog','cloud','backlog','GOOG','亿美元','quarterly','reported','与其他公司RPO定义不同，不直接相加。'],
 ['ORCL.cloud_margin','Oracle云业务营业利润率','Oracle cloud operating margin','cloud','cloud_margin','ORCL','%','quarterly','reported','尚未取得独立云业务可比利润序列。'],
 ['PROJECT.announcements','公开样本项目公告数量','Announced data center projects','projects','announcements','公开项目样本','个','quarterly','project_announcement','项目库尚待去重、公告日期与状态逐项核验。'],
 ['PROJECT.investment','公开项目投资金额','Announced project investment','projects','project_investment','公开项目样本','原始币种','quarterly','project_announcement','不混加不同币种；投资公告不是实际完工。'],
 ['PROJECT.operational_capacity','公开项目新增投运容量','New operational capacity','projects','operational_capacity','公开项目样本','MW','quarterly','project_announcement','未落实的地区为数据不足，不能显示零。'],
 ['PROJECT.construction_capacity','公开项目在建容量','Capacity under construction','projects','construction_capacity','公开项目样本','MW','quarterly','project_announcement','规划、审批、在建、部分投运与已投运分开。'],
 ['POWER.load','重点电力市场负荷','Regional electricity load','power','load','美国重点区域','MW','monthly','official','负荷不等于容量，不单凭上升归因于数据中心需求。'],
 ['POWER.interconnection','电网接入等待容量','Grid interconnection queue capacity','power','interconnection','美国重点区域','MW','annual','official','发电侧排队容量不代表可供数据中心使用的电力容量。'],
 ['POWER.contract_price','数据中心实际合同电价','Data center contracted electricity price','power','contract_price','数据中心','美分/kWh','monthly','reported','采购合同尚未披露；不以原油或区域零售均价替代。'],
 ['POWER.equipment_price','变压器及电气设备价格代理','Transformer and electrical equipment price proxy','power','equipment_price','美国','指数','monthly','proxy','待核验BLS行业覆盖、基期与历史序列。'],
 ['VRT.backlog','电力设备订单余额','Electrical infrastructure backlog','power','backlog','VRT','亿美元','quarterly','reported','待核对公司正式披露与历史可比口径。'],
 ['ETN.gross_margin','电力设备企业毛利率','Electrical equipment gross margin','power','gross_margin','ETN','%','quarterly','reported','用于检验成本转嫁与盈利兑现，尚待接入。'],
 ['DELL.server_revenue','服务器与网络收入','Servers and networking revenue','servers','server_revenue','DELL','亿美元','quarterly','reported','传统服务器和AI服务器口径须分开。'],
 ['DELL.backlog','AI服务器订单余额','AI server backlog','servers','backlog','DELL','亿美元','quarterly','reported','待核对订单取消、交付和确认时点。'],
 ['DELL.inventory','期末库存','Inventories','servers','inventory','DELL','亿美元','quarterly','reported','需与交付和收入共同观察。'],
 ['DELL.inventory_days','库存周转天数','Inventory days','servers','inventory_days','DELL','天','quarterly','calculated','平均库存/当季销售成本×当季实际天数，缺输入不计算。'],
 ['DELL.gross_margin','GAAP毛利率','GAAP gross margin','servers','gross_margin','DELL','%','quarterly','reported','毛利率不能用收入增速替代。'],
 ['HPE.server_revenue','服务器收入','Server revenue','servers','server_revenue','HPE','亿美元','quarterly','reported','保留实际财年季度。'],
 ['INDUSTRY.ai_shipments','AI服务器出货量','AI server shipments','servers','shipments','全球','台','quarterly','third_party','依赖商业研究数据，待授权；不拼接新闻估计。'],
 ['AMD.datacenter_revenue','数据中心业务收入','Data Center segment revenue','semiconductor','datacenter_revenue','AMD','亿美元','quarterly','reported','含CPU与GPU，不等于纯AI加速器收入。'],
 ['AMD.gross_margin','GAAP毛利率','GAAP gross margin','semiconductor','gross_margin','AMD','%','quarterly','reported','待正式财报历史核验。'],
 ['TSM.revenue','晶圆代工营业收入','Foundry revenue','semiconductor','revenue','TSM','亿新台币','monthly','reported','公司全部收入不等于AI需求；保留新台币。'],
 ['TSM.advanced_node_share','先进制程收入占比','Advanced node revenue share','semiconductor','advanced_node_share','TSM','%','quarterly','reported','制程定义随公司披露保存，不混用节点口径。'],
 ['TSM.packaging_capacity','先进封装产能','Advanced packaging capacity','semiconductor','packaging_capacity','TSM','公司披露单位','quarterly','guidance','公开指引与已实现产能分开，待接入。'],
 ['MU.inventory_days','存储库存周转天数','Memory inventory days','semiconductor','inventory_days','MU','天','quarterly','calculated','待财报收入、销售成本和库存核验。'],
 ['MEMORY.hbm_price','HBM价格','HBM contract price','semiconductor','memory_price','全球','来源报价单位','monthly','third_party','待授权的稳定报价，不使用转载数据。'],
 ['MEMORY.dram_price','DRAM价格','DRAM contract price','semiconductor','memory_price','全球','来源报价单位','monthly','third_party','待接入允许展示的报价来源。'],
 ['MEMORY.nand_price','NAND价格','NAND contract price','semiconductor','memory_price','全球','来源报价单位','monthly','third_party','待接入允许展示的报价来源。']
].map(([id,nameZh,nameEn,category,family,entity,unit,frequency,valueType,note])=>({id,nameZh,nameEn,category,family,entity,unit,frequency,valueType,note,sourceName:category==='projects'?'公司与政府项目公告':category==='power'?'EIA / 公司IR':'公司IR / 待授权行业来源',sourceUrl:category==='projects'?source.projects:category==='power'?source.eia:valueType==='third_party'?source.wsts:source.company,methodology:note,aiChainStage:[category],isComparableAcrossEntities:false,normalUpdateDelayDays:frequency==='quarterly'?65:70,recommendationEligible:valueType!=='third_party'&&valueType!=='guidance',exportAllowed:false,aggregation:'none'}));
