import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {parseFredCsv,changeRate,monthlyDiff,movingAverage,metrics,normalizeCommon,monthlyMean,selectRange} from '../lib/calculations.mjs';
const data=JSON.parse(fs.readFileSync(new URL('../data/latest.json',import.meta.url),'utf8'));
const series=id=>data.series[id].observations;
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
test('Missing months are not substituted with preceding rows or zero',()=>{const p=[{date:'2024-01-01',value:100},{date:'2024-03-01',value:105},{date:'2025-01-01',value:110},{date:'2025-03-01',value:null}];near(changeRate(p,12)[2].value,10);assert.equal(changeRate(p,1)[1].value,null);assert.equal(changeRate(p,12)[3].value,null);assert.equal(monthlyDiff(p)[1].value,null)});
test('Moving means require contiguous periods including all valid values',()=>{const p=[{date:'2026-01-03',value:1},{date:'2026-01-10',value:2},{date:'2026-01-17',value:3},{date:'2026-01-24',value:4}];near(movingAverage(p,4,'weekly')[3].value,2.5);assert.equal(movingAverage([p[0],p[1],p[3],{date:'2026-01-31',value:8}],4,'weekly')[3].value,null);assert.equal(movingAverage(p.map((r,i)=>i===1?{...r,value:null}:r),4,'weekly')[3].value,null)});
test('Percent and percentage point changes remain distinct; no divide by zero',()=>{near(metrics([{date:'a',value:4},{date:'b',value:4.25}]).previous,.25);near(metrics([{date:'a',value:100},{date:'b',value:110}],true).range,10);assert.equal(metrics([{date:'a',value:0},{date:'b',value:10}],true).range,null)});
test('Monthly comparison uses shared dates and never fills missing commodities',()=>{const a=[{date:'2026-01-01',value:20},{date:'2026-02-01',value:30},{date:'2026-03-01',value:40}];const b=[{date:'2026-01-01',value:null},{date:'2026-02-01',value:100},{date:'2026-03-01',value:150}];const normalized=normalizeCommon([a,b]);assert.deepEqual(normalized.map(p=>p.date),['2026-02-01','2026-03-01']);near(normalized[0].s0,100);near(normalized[0].s1,100);near(normalized[1].s0,400/3);near(normalized[1].s1,150);assert.deepEqual(monthlyMean([{date:'2026-01-01',value:10},{date:'2026-01-02',value:null},{date:'2026-01-03',value:20}]),[{date:'2026-01-01',value:15}])});
test('FRED parser rejects bad numeric values, duplicate dates and markup',()=>{assert.throws(()=>parseFredCsv('<html>error</html>'));assert.throws(()=>parseFredCsv('DATE,A\n2026-01-01,oops'));assert.throws(()=>parseFredCsv('DATE,A\n2026-01-01,1\n2026-01-01,2'));assert.equal(parseFredCsv('DATE,A\n2026-01-01,')[0].value,null)});
const report={checkedAt:new Date().toISOString(),rawSamples:[],chartSamples:[]};
test('Every FRED source: three imported history points match archived raw downloads',()=>{for(const [id,s] of Object.entries(data.series)){if(['COPPER','GOLD','SILVER'].includes(id))continue;const prefix=s.revision.split('_').at(-1);const directory=new URL('../data/versions/'+id+'/',import.meta.url);const file=fs.readdirSync(directory).find(name=>name.startsWith(prefix));assert.ok(file,id+' raw archive exists');const raw=parseFredCsv(fs.readFileSync(new URL(file,directory),'utf8'));const map=new Map(raw.map(p=>[p.date,p.value]));const valid=s.observations.filter(p=>p.value!==null);for(const index of [0,Math.floor(valid.length/2),valid.length-1]){const p=valid[index];near(p.value,map.get(p.date));report.rawSamples.push({id,...p,sourceFile:file})}}});
test('12 chart groups: three historical points each agree with source transformations',()=>{
 const get=(id,date)=>series(id).find(p=>p.date===date)?.value;
 const prev=(date,months)=>{const [y,m]=date.split('-').map(Number);const d=new Date(Date.UTC(y,m-1-months,1));return d.toISOString().slice(0,10)};
 const configurations=[['claims','ICSA',series('ICSA').map(p=>({...p,value:p.value===null?null:p.value/1000})),p=>get('ICSA',p.date)/1000],['unemployment','UNRATE',series('UNRATE'),p=>get('UNRATE',p.date)],['payrolls','PAYEMS',monthlyDiff(series('PAYEMS')),p=>get('PAYEMS',p.date)-get('PAYEMS',prev(p.date,1))],['cpi','CPIAUCNS',changeRate(series('CPIAUCNS'),12),p=>(get('CPIAUCNS',p.date)/get('CPIAUCNS',prev(p.date,12))-1)*100],['pce','PCEPILFE',changeRate(series('PCEPILFE'),12),p=>(get('PCEPILFE',p.date)/get('PCEPILFE',prev(p.date,12))-1)*100],...['DFEDTARL','DCOILBRENTEU','COPPER','GOLD','SILVER','DFII10','NFCI'].map((id,i)=>[['policy','brent','copper','gold','silver','yields','nfci'][i],id,series(id),p=>get(id,p.date)])];
 for(const [group,id,points,expected] of configurations){const valid=points.filter(p=>p.value!==null);for(const index of [0,Math.floor(valid.length/2),valid.length-1]){const p=valid[index];near(p.value,expected(p));report.chartSamples.push({group,id,date:p.date,actual:p.value,expected:expected(p)})}}
 // Verify every auxiliary transformed series and moving mean too.
 for(const [id,lag] of [['CPILFENS',12],['CPIAUCSL',1],['CPILFESL',1],['PCEPI',12],['PCEPI',1],['PCEPILFE',1]]){const valid=changeRate(series(id),lag).filter(p=>p.value!==null);for(const p of [valid[0],valid[Math.floor(valid.length/2)],valid.at(-1)])near(p.value,(get(id,p.date)/get(id,prev(p.date,lag))-1)*100)}
 const means=movingAverage(series('ICSA'),4,'weekly');for(const i of [3,1000,means.length-1]){near(means[i].value,series('ICSA').slice(i-3,i+1).reduce((s,p)=>s+p.value,0)/4)}
 fs.mkdirSync(new URL('../docs/',import.meta.url),{recursive:true});fs.writeFileSync(new URL('../docs/verification.json',import.meta.url),JSON.stringify(report,null,2));assert.equal(report.chartSamples.length,36)
});

