"use client";
import { useEffect, useMemo, useState } from 'react';
import { ResponsiveContainer, ComposedChart, Line, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Brush, ReferenceLine, ReferenceDot } from 'recharts';
import { ArrowDownToLine, ArrowUpRight, ChartColumn, ChartLine, Info } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { type Dataset, colors, makeChart, firstValues, format, deltaFormat, beijing, metadata, sourceLink } from '@/lib/data';
import type { Group } from '@/lib/groups';
import { metrics, selectRange } from '@/lib/calculations.mjs';
export function RangeButtons({value,onChange,available=['1','3','5','all']}:{value:string;onChange:(value:string)=>void;available?:string[]}){return <div className="range-selector">{[['1','近一年'],['3','三年'],['5','五年'],['all','全部']].map(([id,label])=><Button key={id} variant="ghost" aria-pressed={value===id} className={value===id?'selected':''} disabled={!available.includes(id)} onClick={()=>onChange(id)}>{label}</Button>)}</div>}
export default function ChartCard({group,data,range:globalRange,compact=false}:{group:Group;data:Dataset;range:string;compact?:boolean}){
 const [range,setRange]=useState(globalRange),[mode,setMode]=useState('yoy'),[style,setStyle]=useState(group.kind==='bar'?'bar':'line'),[hidden,setHidden]=useState<number[]>([]),[zoom,setZoom]=useState<{startIndex?:number;endIndex?:number}|null>(null),[details,setDetails]=useState(false);
 // The page-level range is an explicit external control. Reset the local brush
 // in the same commit so the selected period and chart window never disagree.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{setRange(globalRange);setZoom(null)},[globalRange]);
 const chart=useMemo(()=>makeChart(group,data,mode),[group,data,mode]);
 const hasValue=(r:Record<string,unknown>)=>Object.entries(r).some(([key,v])=>key!=='date'&&v!==null);
 const firstIndex=chart.rows.findIndex(hasValue),lastIndex=chart.rows.findLastIndex(hasValue);
 const nonEmpty=firstIndex<0?[]:chart.rows.slice(firstIndex,lastIndex+1);
 const available=['1','3','5'].filter(y=>nonEmpty.length>0&&Date.parse(nonEmpty.at(-1)!.date)-Date.parse(nonEmpty[0].date)>=Number(y)*365*86400000).concat('all');
 const effective=available.includes(range)?range:'all';
 const rows=selectRange(nonEmpty,effective);const visibleRows=zoom?rows.slice(zoom.startIndex??0,(zoom.endIndex??rows.length-1)+1):rows;
 const isPrice=group.category===2;const unit=group.unit;const deltaUnit=isPrice?'%':group.id==='nfci'?'指数点':unit==='%'?'个百分点':unit;
 const stats=metrics(firstValues(chart.rows),isPrice),selectedStats=metrics(firstValues(visibleRows),isPrice),digits=group.id==='claims'||group.id==='payrolls'?1:group.id==='nfci'?3:2;
 const series=chart.ids.map(id=>data.series[id]).filter(Boolean);
 const exportAllowed=chart.ids.every(id=>metadata[id]?.exportAllowed);
 const failed=series.some(s=>['cached','fetch_failed'].includes(s.status));
 function exportCsv(){const rowsOut=[['观测日期',...chart.names.map(n=>n+' ('+unit+')')],...visibleRows.map((r:Record<string,unknown>)=>[r.date,...chart.names.map((_,i)=>r['s'+i]??'')]),[],['来源',...chart.ids.map(sourceLink)],['计算',group.kind!=='inflation'?(group.id==='claims'?'ICSA / 1000，连续四周均值':group.id==='payrolls'?'本月 PAYEMS - 上月 PAYEMS；连续三月均值':'来源原始数值，未做同比转换'):mode==='yoy'?'同比 = 本期 / 上年同月 - 1；百分数':mode==='mom'?'环比 = 本期 / 上月 - 1；百分数':'原始值'],['获取时间',...series.map(s=>s.fetchedAt??'')],['版本',...series.map(s=>s.revision??'')]];
 const blob=new Blob(['\uFEFF'+rowsOut.map(r=>r.map((v:unknown)=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=group.id+'-'+effective+'-'+mode+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const latestText=stats.last?.date??'暂无观测';
 const publication=series[0]?.publication;
 return <section id={group.id} className={'chart-card '+(compact?'compact':'')} aria-label={group.title}>
 <div className="chart-title"><div><h3>{group.title}</h3><div className="chart-subtitle">{group.kind==='inflation'?(mode==='yoy'?'同比变化':'环比变化'):group.id==='yields'?'实际收益率 · 名义收益率':group.id==='claims'?'季调 · 四周移动平均':group.category===2&&group.frequency==='月度'?'世界银行 · 月度均价':metadata[group.series[0]]?.seasonal}</div></div><span className="frequency">{group.frequency}</span></div>
 <div className="stat-row"><div className="chart-stat">{format(stats.last?.value,digits)} <small>{unit}</small></div><span className={'delta '+(stats.previous===null?'neutral':stats.previous>0?'up':stats.previous<0?'down':'neutral')}>{stats.previous===null?'—':(stats.previous>0?'↑ ':stats.previous<0?'↓ ':'→ ')+deltaFormat(stats.previous,digits)+' '+deltaUnit}<small>较上期</small></span></div>
 <div className="chart-date">{chart.names[0]} · 最新有效观测 {latestText}{failed&&<span className="warning-inline"> · 获取失败，保留缓存</span>}</div>
 {publication&&<div className="next-release">{publication.state==='awaiting_source'?'已到计划发布时间，等待来源更新':publication.state==='delayed'?'来源发布延迟，继续展示最后成功数据':publication.state==='calendar_unavailable'?'发布日历暂不可用，按日检查来源':publication.nextReleaseAt?'下次计划发布：'+beijing(publication.nextReleaseAt)+'（北京）':'按来源节奏检查，等待下一次发布'}{publication.calendarSource?.startsWith('https://')&&<a href={publication.calendarSource} target="_blank" rel="noreferrer"> · 日历 ↗</a>}</div>}
 <div className="chart-controls"><RangeButtons value={effective} available={available} onChange={v=>{setRange(v);setZoom(null)}}/><div className="chart-actions">{group.kind==='inflation'&&<div className="mode-switch">{['yoy','mom'].map(m=><Button key={m} variant="ghost" aria-pressed={mode===m} className={mode===m?'selected':''} onClick={()=>{setMode(m);setZoom(null);setStyle(m==='mom'?'bar':'line')}}>{m==='yoy'?'同比':'环比'}</Button>)}</div>}{group.kind!=='step'&&<Button variant="ghost" size="icon-sm" aria-label={style==='line'?'切换为柱状图':'切换为折线图'} title={style==='line'?'切换为柱状图':'切换为折线图'} onClick={()=>setStyle(s=>s==='line'?'bar':'line')}>{style==='line'?<ChartColumn/>:<ChartLine/>}</Button>}<Button variant="ghost" size="icon-sm" aria-label={exportAllowed?'导出 '+group.title+' CSV':'此来源尚未开放导出'} title={exportAllowed?'导出所选区间 CSV':'NFCI 导出许可待核验'} disabled={!exportAllowed||!rows.length} onClick={exportCsv}><ArrowDownToLine/></Button></div></div>
 {rows.length?<><div className="data-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={rows} margin={{top:10,right:6,bottom:0,left:-17}} accessibilityLayer><CartesianGrid vertical={false} stroke="#e9eff0" strokeDasharray="3 4"/><XAxis dataKey="date" tickFormatter={(date:string)=>date.slice(2,7).replace('-','/')} minTickGap={35} tickLine={false} axisLine={false} tick={{fontSize:11,fill:'#90a0a7'}}/><YAxis domain={['auto','auto']} tickLine={false} axisLine={false} tick={{fontSize:11,fill:'#90a0a7'}} tickFormatter={v=>Math.abs(v)>=10000?(v/1000).toFixed(0)+'k':format(v,Math.abs(v)<2?2:1)} width={64}/><Tooltip labelFormatter={label=>String(label)} formatter={(v,name)=>[format(Number(v),digits)+' '+unit,name]} contentStyle={{fontSize:12,border:'1px solid #dae7e2',borderRadius:7,boxShadow:'0 5px 18px #234a3c12'}}/>{(group.id==='nfci'||group.id==='payrolls')&&<ReferenceLine y={0} stroke="#83969c" strokeDasharray="4 4"/>}{group.id==='pce'&&mode==='yoy'&&<ReferenceLine y={2} stroke="#b3aaa1" strokeDasharray="4 5" label={{value:'总体 PCE 目标 2%',position:'insideTopRight',fill:'#a39a90',fontSize:10}}/>}{chart.names.map((name,i)=>hidden.includes(i)?null:style==='bar'&&i===0?<Bar key={name} dataKey={'s'+i} name={name} fill="#80b9aa" radius={[2,2,0,0]} isAnimationActive={false}/>:<Line key={name} type={group.kind==='step'?'stepAfter':'linear'} dataKey={'s'+i} name={name} stroke={colors[i]} strokeWidth={i===0?2:1.7} dot={false} connectNulls={false} isAnimationActive={false}/>)}{group.kind==='step'&&rows.filter((r:Record<string,unknown>,i:number)=>i>0&&r.s0!==rows[i-1].s0).map((r:Record<string,unknown>)=><ReferenceDot key={String(r.date)} x={String(r.date)} y={Number(r.s0)} r={3} fill={colors[0]} stroke="white"/>)}<Brush dataKey="date" height={17} stroke="#cbdad5" fill="#f6f9f8" travellerWidth={7} tickFormatter={(d:string)=>d.slice(0,7)} onChange={z=>setZoom(z)} startIndex={zoom?.startIndex} endIndex={zoom?.endIndex}/></ComposedChart></ResponsiveContainer></div><div className="chart-legend">{chart.names.map((name,i)=><Button key={name} variant="ghost" aria-pressed={!hidden.includes(i)} className={hidden.includes(i)?'muted-legend':''} onClick={()=>setHidden(h=>h.includes(i)?h.filter(n=>n!==i):[...h,i])}><i style={{background:colors[i]}}/>{name}</Button>)}<span className="zoom-tip">拖动下方滑块缩放</span></div></>:<div className="empty-chart"><Info size={22}/><p>{series.some(s=>s.status==='fetch_failed')?'来源获取失败，暂无可用缓存':'来源未配置或尚未发布'}</p></div>}
 <div className="period-change"><span>所选区间 {selectedStats.first?.date??'—'} — {selectedStats.last?.date??'—'}</span><strong className={(selectedStats.range??0)>0?'up':(selectedStats.range??0)<0?'down':'neutral'}>{selectedStats.range==null?'—':((selectedStats.range??0)>0?'+':'')+format(selectedStats.range,digits)+' '+deltaUnit}</strong></div>
 <div className="chart-explanation"><strong>如何理解</strong><p>{group.read}</p><strong className="impact-label">对 AI 产业链的影响</strong><p>{group.impact}</p><div className="sector-tags">{group.sectors.map(s=><span key={s}>{s}</span>)}</div></div>
 <div className="chart-source"><a href={sourceLink(group.series[0])} target="_blank" rel="noreferrer">{metadata[group.series[0]]?.source} ↗</a><Button variant="ghost" onClick={()=>setDetails(d=>!d)} aria-expanded={details}>数据详情 <Info size={12}/></Button></div>
 <div className="fetch-timestamp">成功获取：{beijing(series[0]?.fetchedAt)}（北京）</div>
 {details&&<div className="metadata-detail">{chart.ids.map(id=>{const s=data.series[id];return <div key={id}><a href={sourceLink(id)} target="_blank" rel="noreferrer">{id} · {metadata[id]?.name} <ArrowUpRight size={12}/></a><p>单位：{metadata[id]?.unit} · {metadata[id]?.seasonal} · 状态：{s?.status==='ready'?'真实历史数据':s?.status==='cached'?'获取失败，展示缓存':s?.status==='fetch_failed'?'获取失败':'来源未配置'}</p><p>最近成功获取：{beijing(s?.fetchedAt)}（北京）<br/>来源发布时间：{beijing(s?.sourcePublishedAt)}<br/>修订版本：{s?.revision??'—'}</p>{metadata[id]?.license&&<p>{metadata[id].license}</p>}</div>})}<p>缺值保持为空。同比额外使用前十二个月基期；变化值以原始精度计算。</p></div>}
 </section>
}



