// Calendar-aligned calculations. Nulls remain null; base periods must exist.
export function monthOffset(date,offset){const d=new Date(date+'T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+offset);return d.toISOString().slice(0,7)+'-01'}
export function changeRate(points,lag){const map=new Map(points.map(p=>[p.date,p.value]));return points.map(p=>{const base=map.get(monthOffset(p.date,-lag));return {...p,value:p.value!==null&&base!==null&&base!==undefined&&base!==0?(p.value/base-1)*100:null}})}
export function monthlyDiff(points){const map=new Map(points.map(p=>[p.date,p.value]));return points.map(p=>{const base=map.get(monthOffset(p.date,-1));return {...p,value:p.value!==null&&base!==null&&base!==undefined?p.value-base:null}})}
export function movingAverage(points,n,frequency){return points.map((p,i)=>{const window=points.slice(i-n+1,i+1);let valid=i>=n-1&&window.length===n&&window.every(q=>q.value!==null);for(let j=1;j<window.length&&valid;j++){valid=frequency==='weekly'?Date.parse(window[j].date)-Date.parse(window[j-1].date)===7*86400000:monthOffset(window[j-1].date,1)===window[j].date}return {...p,value:valid?window.reduce((s,q)=>s+q.value,0)/n:null}})}
export function selectRange(points,years){if(!points.length||years==='all')return points;const last=points.at(-1).date;const d=new Date(last+'T00:00:00Z');d.setUTCFullYear(d.getUTCFullYear()-Number(years));return points.filter(p=>p.date>=d.toISOString().slice(0,10))}
export function metrics(points,percent=false){const valid=points.filter(p=>p.value!==null&&Number.isFinite(p.value));const last=valid.at(-1),prev=valid.at(-2),first=valid[0];const delta=(a,b)=>!a||!b?null:percent?(b.value===0?null:(a.value/b.value-1)*100):a.value-b.value;return {last,prev,first,previous:delta(last,prev),range:delta(last,first)}}
export function monthlyMean(points){const bins=new Map();for(const p of points){const key=p.date.slice(0,7)+'-01';if(!bins.has(key))bins.set(key,[]);if(p.value!==null)bins.get(key).push(p.value)}return [...bins].map(([date,values])=>({date,value:values.length?values.reduce((a,b)=>a+b,0)/values.length:null}))}
export function completeMonthlyMean(points,asOf=new Date().toISOString().slice(0,10)){const valid=points.filter(p=>p.value!==null);if(!valid.length)return [];const firstMonth=valid[0].date.slice(0,7);const lastMonth=valid.at(-1).date.slice(0,7);const currentMonth=asOf.slice(0,7);const cutoff=lastMonth<currentMonth?lastMonth:currentMonth;return monthlyMean(points).filter(p=>p.date.slice(0,7)>firstMonth&&p.date.slice(0,7)<cutoff)}
export function normalizeCommon(series){if(!series.length)return [];const maps=series.map(s=>new Map(s.map(p=>[p.date,p.value])));const dates=series[0].map(p=>p.date).filter(date=>maps.every(m=>m.get(date)!==null&&m.get(date)!==undefined));const first=dates[0];if(!first||maps.some(m=>m.get(first)===0))return [];return dates.map(date=>({date,...Object.fromEntries(maps.map((m,i)=>['s'+i,m.get(date)/m.get(first)*100]))}))}
export function parseFredCsv(csv){const lines=csv.trim().split(/\r?\n/);if(!/^(observation_date|DATE),/.test(lines[0]))throw new Error('Invalid FRED CSV header');const seen=new Set();return lines.slice(1).map(line=>{const [date,raw]=line.split(',');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||seen.has(date))throw new Error('Invalid or duplicate observation date');seen.add(date);const value=!raw||raw==='.'?null:Number(raw);if(value!==null&&!Number.isFinite(value))throw new Error('Invalid numeric observation');return {date,value}}).sort((a,b)=>a.date.localeCompare(b.date))}
